name: Staging

on:
  push:
    branches:
      - main
      - staging

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip build

      - name: Build wheels
        run: |
          python -m build

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*.whl
