name: Staging

on:
  push:
    branches:
      - main
      - staging

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        run: |
          pip wheel -w wheelhouse/ .

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
